In [2]:
import numpy as np

In [6]:
# 1. NumPy program to create an array of 10 zeros,10 ones, 10 fives.

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
c = np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [42]:
# 2.  NumPy program to create an array of all the even integers from 30 to 70.

z = np.arange(30, 70, 2)
z

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [53]:
# 3. NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

z1 = np.ones((10, 10))
z1[1:-1, 1:-1] = 0
z1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
# 4. NumPy program to reverse an array (first element becomes last).

z2 = np.arange(12, 38)
print("Original array:")
print(z2)
print("Reverse array:")
z2 = z2[::-1]
print(z2)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [3]:
#  5. NumPy program to find common values between two arrays.
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]


In [17]:
# 6. NumPy program to create an array. Then change it to a new shape of the array, without changing its data.

x = np.array([1, 2, 3, 4, 5, 6])
print("array x:", x)
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)

array x: [1 2 3 4 5 6]
Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]


In [16]:
# 7.  NumPy program to concatenate two 2-dimensional arrays in the following manner as below.

x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])
z = np.concatenate((x, y), 1)
print(z)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [23]:
# 8. NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

z = np.arange(1, 15)
print("Original array:",z)
print("After splitting:")
print(np.split(z, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [26]:
#  9. NumPy program to create an 1-D array of 20 elements. Now create a new array of shape (5, 4) from the said array, then restores the reshaped array into a 1-D array.

array1 = np.arange(0, 20)
print("Original array:")
print(array1)
print("\nNew array of shape(5, 4):")
new_array = array1.reshape(5, 4)
print(new_array) 
print("\nRestore the reshaped array into a 1-D array:")
print(new_array.flatten())

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

New array of shape(5, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Restore the reshaped array into a 1-D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
# 10. NumPy program to create an array of 4,5 shape and swap column1 with column4.

array2 = np.arange(20).reshape(4,5)
print("Original array:")
print(array2)
print("\nAfter swapping column1 with column4:")
array2[:,[0,3]] = array2[:,[3,0]]
print(array2)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

After swapping column1 with column4:
[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]
